(function () {
  'use strict';

  /* Known platforms, in display order. Keys match the `links` object in
     data.js; icons live in ../images/icons/. */
  const PLATFORMS = [
    { key: 'bandcamp',     label: 'Bandcamp',      icon: 'bandcamp.svg' },
    { key: 'spotify',      label: 'Spotify',       icon: 'spotify.svg' },
    { key: 'appleMusic',   label: 'Apple Music',   icon: 'applemusic.svg' },
    { key: 'youtubeMusic', label: 'YouTube Music', icon: 'youtube.svg' },
    { key: 'youtube',      label: 'YouTube',       icon: 'youtube.svg' },
    { key: 'pandora',      label: 'Pandora',       icon: 'pandora.svg' },
    { key: 'itunes',       label: 'iTunes Store',  icon: 'itunes.svg' },
    { key: 'deezer',       label: 'Deezer',        icon: 'deezer.svg' },
    { key: 'amazonMusic',  label: 'Amazon Music',  icon: 'amazonmusic.svg' },
    { key: 'tidal',        label: 'TIDAL',         icon: 'tidal.svg' },
    { key: 'qobuz',        label: 'Qobuz',         icon: 'qobuz.svg' }
  ];

  const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'];

  const collator = new Intl.Collator(undefined, { sensitivity: 'base' });
  const compareText = (a, b) => collator.compare(a || '', b || '');

  function escapeHTML(s) {
    return (s == null ? '' : String(s)).replace(/[&<>"']/g, (m) => ({
      '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
    }[m]));
  }

  /* Every release has its own page at /releases/<slug>/ (generated by
     scripts/build-release-pages.js so link unfurls get the album art and
     title). Those pages sit one level deeper than the archive, so in-page
     links and asset paths are root-absolute rather than document-relative. */
  const LIST_URL = '/releases/';
  const releaseHref = (slug) => `/releases/${encodeURIComponent(slug)}/`;

  function slugFromPath(pathname) {
    const m = /\/releases\/([^/]+)\/?$/.exec(pathname || '');
    if (!m || /\.html?$/i.test(m[1])) return null;
    try { return decodeURIComponent(m[1]); } catch (e) { return m[1]; }
  }

  /* Accepts "YYYY-MM-DD" or "YYYY-MM". */
  function parseReleaseDate(s) {
    const parts = String(s || '').split('-').map((p) => parseInt(p, 10));
    if (!parts.length || Number.isNaN(parts[0])) return null;
    return { y: parts[0], m: parts[1] || 1, d: parts[2] || null };
  }

  function dateMs(s) {
    const p = parseReleaseDate(s);
    return p ? new Date(p.y, p.m - 1, p.d || 1).getTime() : 0;
  }

  function formatReleaseDate(s) {
    const p = parseReleaseDate(s);
    if (!p) return '';
    const month = MONTHS[p.m - 1] || '';
    return p.d ? `${month} ${p.d}, ${p.y}` : `${month} ${p.y}`;
  }

  /* Releases with a future releaseDate are kept in the catalog (so they can
     be edited ahead of time and validated by check-catalog.js) but must stay
     invisible to the public until that date: out of the list, out of search,
     out of "did you mean", and out of direct ?r=<slug> access. Computed once
     against the visitor's local calendar date at load. */
  const TODAY_MS = (() => {
    const now = new Date();
    return new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
  })();

  function buildDerived(rel) {
    const haystack = [
      rel.title, rel.subtitle, rel.type, rel.description, rel.upc, rel.slug,
      rel.releaseDate, formatReleaseDate(rel.releaseDate),
      (rel.tags || []).join(' '),
      (rel.tracks || []).map((t) =>
        t.title + ' ' + (t.isrc || '') + ' ' + (t.artists || []).join(' ')).join(' ')
    ].join(' ').toLowerCase();
    const relDateMs = dateMs(rel.releaseDate);
    return { ...rel, dateMs: relDateMs, isReleased: relDateMs <= TODAY_MS, searchHaystack: haystack };
  }

  const TRACK_CATALOG = typeof TRACKS !== 'undefined' && TRACKS ? TRACKS : {};
  const RELEASE_CATALOG = typeof RELEASES !== 'undefined' && RELEASES ? RELEASES : [];
  const catalogErrors = [];

  for (const [trackId, track] of Object.entries(TRACK_CATALOG)) {
    if (!track || typeof track !== 'object') {
      catalogErrors.push(`Track ${trackId} is not an object.`);
      continue;
    }
    if (trackId.startsWith('isrc:') && trackId !== `isrc:${track.isrc || ''}`) {
      catalogErrors.push(`Track ${trackId} does not match its stored ISRC.`);
    }
  }

  function resolveTrackReference(ref, releaseSlug) {
    if (!ref || typeof ref !== 'object' || !ref.trackId) {
      catalogErrors.push(`Release ${releaseSlug} has an invalid track reference.`);
      return null;
    }
    const canonical = TRACK_CATALOG[ref.trackId];
    if (!canonical) {
      catalogErrors.push(`Release ${releaseSlug} references missing track ${ref.trackId}.`);
      return null;
    }
    return {
      ...canonical,
      title: Object.prototype.hasOwnProperty.call(ref, 'title') ? ref.title : canonical.title,
      duration: Object.prototype.hasOwnProperty.call(ref, 'duration') ? ref.duration : canonical.duration
    };
  }

  // Resolve normalized track references once at startup. Invalid references
  // are omitted so one bad catalog row cannot prevent the archive from loading.
  const seenSlugs = new Set();
  const DB = RELEASE_CATALOG.flatMap((rel) => {
    if (!rel || !rel.slug) {
      catalogErrors.push('A release is missing its slug.');
      return [];
    }
    if (seenSlugs.has(rel.slug)) {
      catalogErrors.push(`Duplicate release slug ${rel.slug}; the later entry was ignored.`);
      return [];
    }
    seenSlugs.add(rel.slug);
    const refs = Array.isArray(rel.tracklist) ? rel.tracklist : [];
    if (!Array.isArray(rel.tracklist)) {
      catalogErrors.push(`Release ${rel.slug} is missing its tracklist array.`);
    }
    const trackIds = [];
    const seenTrackIds = new Set();
    const tracks = [];
    for (const ref of refs) {
      if (ref && ref.trackId) {
        if (seenTrackIds.has(ref.trackId)) {
          catalogErrors.push(`Release ${rel.slug} contains duplicate track ${ref.trackId}.`);
        }
        seenTrackIds.add(ref.trackId);
        trackIds.push(ref.trackId);
      }
      const track = resolveTrackReference(ref, rel.slug);
      if (track) tracks.push(track);
    }
    return [buildDerived({ ...rel, tracks, trackIds })];
  });

  if (catalogErrors.length) {
    console.error(`Pokestir release catalog: ${catalogErrors.length} validation error(s).`, catalogErrors);
  }

  /* A recording can appear on multiple releases: most of the old
     singles' tracks were re-released on the newer compilation albums — a
     new UPC around the same underlying recordings. Derive that membership
     from shared normalized track IDs rather than baking it into data.js, so it can
     never drift out of sync with the catalog. A release is "included in"
     another when every one of its tracks appears there and the
     other release has more tracks (the pointer only goes single -> album,
     never sideways between equal releases or back down). */
  for (const rel of DB) {
    rel.trackIdSet = new Set(rel.trackIds);
  }
  for (const rel of DB) {
    rel.includedIn = !rel.trackIdSet.size ? [] : DB.filter((other) =>
      other !== rel && other.isReleased &&
      (other.tracks || []).length > (rel.tracks || []).length &&
      [...rel.trackIdSet].every((trackId) => other.trackIdSet.has(trackId))
    ).sort((a, b) => b.dateMs - a.dateMs);
    // searching a compilation's name should also surface its singles
    if (rel.includedIn.length) {
      rel.searchHaystack += ' ' + rel.includedIn.map((h) => h.title).join(' ').toLowerCase();
    }
  }

  // Public-facing views (list, search, detail routing, "did you mean") only
  // ever see released entries; DB itself stays complete for the includedIn
  // derivation above and for catalog validation.
  const VISIBLE_DB = DB.filter((rel) => rel.isReleased);

  /* Script-driven motion has to carry its own reduced-motion guard: CSS cannot
     suppress Web Animations. Timings and curves are resolved from the shared
     tokens so this code cannot drift into a second motion vocabulary. */
  const REDUCED = matchMedia('(prefers-reduced-motion: reduce)');
  const MAX_MOTION_TILES = 24;
  const activeGridMotions = new Set();
  let activeRailMotion = null;

  function motionToken(name) {
    return getComputedStyle(document.documentElement).getPropertyValue(name).trim();
  }

  function motionDuration(name) {
    const value = motionToken(name);
    if (value.endsWith('ms')) return parseFloat(value);
    if (value.endsWith('s')) return parseFloat(value) * 1000;
    return 0;
  }

  function trackGridMotion(animation, cleanup) {
    const motion = { animation, cleanup };
    activeGridMotions.add(motion);
    animation.finished.then(cleanup, cleanup).finally(() => activeGridMotions.delete(motion));
  }

  function clearGridMotions() {
    for (const motion of activeGridMotions) {
      motion.animation.cancel();
      motion.cleanup();
    }
    activeGridMotions.clear();
  }

  function nearViewport(rect) {
    return rect.bottom >= 0 && rect.top <= window.innerHeight;
  }

  /* ── Grid motion ──────────────────────────────────────────────────────────
     The same deal the gear grid uses, and for the same reason: tiles are placed
     rather than faded in, arriving from slightly above and slightly larger than
     final, in reading order rather than all on one frame. Twenty-four tiles
     starting together read as a single crossfade of the archive instead of a
     list rearranging.

     Kept as a local copy rather than shared with gear.js. The two grids hold
     different things at different sizes and will diverge before they converge,
     and this file already keeps its own copies of the motion helpers by choice.
     What is genuinely shared is `travelPath`, because a card crossing a grid
     must move on the same law as everything else on the site. */
  const DEAL_STEP = 22;     // ms between consecutive arrivals
  const DEAL_WINDOW = 240;  // ms; every arrival has begun by here

  function dealDelay(index) {
    return Math.min(index * DEAL_STEP, DEAL_WINDOW);
  }

  function dealIn(el, index) {
    const travel = parseFloat(motionToken('--mo-travel')) || 0;
    return el.animate([
      { opacity: 0, transform: `translateY(${-6 * travel}px) scale(1.04)` },
      { opacity: 1, transform: 'translateY(0) scale(1)' }
    ], {
      duration: 260,
      easing: motionToken('--mo-snap'),
      delay: dealDelay(index),
      fill: 'backwards'
    });
  }

  /* Survivors of a search or a sort travel on `travelPath`, so a tile crossing
     the archive takes longer than one shifting a column, and both land with the
     commit and settle the nav pill uses. */
  function moveSurvivor(el, dx, dy, fromOpacity) {
    const MO = window.PokestirMotion;
    const move = MO && MO.travelPath({ x: dx, y: dy }, { x: 0, y: 0 });
    if (!move) {
      return el.animate([
        { opacity: fromOpacity, transform: `translate(${dx}px, ${dy}px)` },
        { opacity: 1, transform: 'translate(0, 0)' }
      ], { duration: motionDuration('--mo-base'), easing: motionToken('--mo-out') });
    }
    const over = move.over;
    return el.animate([
      { opacity: fromOpacity, transform: `translate(${dx}px, ${dy}px)`, easing: 'cubic-bezier(.7,0,.35,1)' },
      { transform: `translate(${move.ux * over}px, ${move.uy * over}px)`, offset: .6, easing: 'cubic-bezier(.4,0,.3,1)' },
      { transform: `translate(${-move.ux * over * .32}px, ${-move.uy * over * .32}px)`, offset: .82, easing: 'cubic-bezier(.4,0,.3,1)' },
      { opacity: 1, transform: 'translate(0, 0)' }
    ], { duration: move.duration, fill: 'backwards' });
  }

  function cancelRailMotion() {
    if (activeRailMotion) activeRailMotion.cancel();
  }

  /* Native smooth scrolling owns its curve, so it cannot share the motion
     language used everywhere around it. A hidden WAAPI driver supplies the
     tokenized easing while rAF applies that eased progress to scrollLeft. */
  /* One tile's worth of horizontal distance, measured live: the rail's column
     width is 280px on desktop and `min(240px, 68vw)` on mobile, so it cannot be
     assumed. Every snap point is a multiple of this. */
  function railStride(rail) {
    const tiles = rail.querySelectorAll('.release-tile');
    if (tiles.length < 2) return Math.max(1, rail.clientWidth || 1);
    return Math.max(1, Math.round(tiles[1].offsetLeft - tiles[0].offsetLeft));
  }

  /* A whole number of tiles, never a fraction of the viewport. */
  function railPage(rail) {
    const stride = railStride(rail);
    return Math.max(1, Math.floor((rail.clientWidth || stride) / stride)) * stride;
  }

  function animateRailBy(rail, distance) {
    cancelRailMotion();
    const start = rail.scrollLeft;
    const max = Math.max(0, rail.scrollWidth - rail.clientWidth);
    /* Land on a snap point. The paging distance used to be `clientWidth * 0.9`,
       which at the real geometry is 3.32 tiles, so every click glided to a
       position that was not a snap point and the snap engine then yanked it
       back by as much as 107px once the glide finished. A smooth move followed
       by an uncontrolled jerk is what made these arrows feel clunky. Rounding
       to the nearest tile also re-aligns the rail if it was left mid-tile by a
       swipe, so the arrows always tidy up rather than compound the offset. */
    const stride = railStride(rail);
    const end = Math.max(0, Math.min(max, Math.round((start + distance) / stride) * stride));
    if (start === end) return;
    if (REDUCED.matches || typeof rail.animate !== 'function') {
      rail.scrollLeft = end;
      return;
    }

    /* Suspended for the duration: while this animation is the thing setting
       scrollLeft, the snap engine has nothing to contribute and every frame it
       touches is a frame it can fight. The landing is already a snap point, so
       restoring it at the end moves nothing. */
    const snapType = rail.style.scrollSnapType;
    rail.style.scrollSnapType = 'none';

    const driver = document.createElement('span');
    driver.className = 'rail-motion-driver';
    driver.setAttribute('aria-hidden', 'true');
    document.body.appendChild(driver);
    /* Distance-scaled on the same law as the nav pill and the gear grid, rather
       than a flat --mo-comp for every hop. A scroll does not get the pill's
       overshoot, though: content that sails past its stop and comes back is
       disorienting to read, and it would hand the snap engine something to
       correct all over again. Only the duration is shared. */
    const MO = window.PokestirMotion;
    const move = MO && MO.travelPath({ x: 0, y: 0 }, { x: Math.abs(end - start), y: 0 });
    const animation = driver.animate([{ opacity: 0 }, { opacity: 1 }], {
      duration: move ? move.duration : motionDuration('--mo-comp'),
      easing: motionToken('--mo-inout'),
      fill: 'both'
    });
    let frame = 0;
    let stopped = false;

    function stop(land, cancelAnimation) {
      if (stopped) return;
      stopped = true;
      if (cancelAnimation) animation.cancel();
      cancelAnimationFrame(frame);
      if (land) rail.scrollLeft = end;
      rail.style.scrollSnapType = snapType;
      driver.remove();
      if (activeRailMotion && activeRailMotion.animation === animation) activeRailMotion = null;
    }

    function step() {
      if (stopped) return;
      const progress = parseFloat(getComputedStyle(driver).opacity) || 0;
      rail.scrollLeft = start + (end - start) * progress;
      frame = requestAnimationFrame(step);
    }

    activeRailMotion = { animation, cancel: () => stop(false, true) };
    animation.finished.then(() => stop(true, false), () => stop(false, false));
    step();
  }

  /* Artwork URLs are stored directly in data.js rather than fetched live in
     the browser — at catalog scale, hundreds of live lookups on page load
     would be slow and unreliable. Elements without artwork keep the CSS
     gradient placeholder. */

  /* Every stored artwork URL is a 1000x1000 crop, because that is the size
     link unfurlers want in og:image. Nothing on the page is anywhere near
     that big: tiles are 196-280px and the detail hero is 172px, so a 1000px
     cover is ~170KB to draw ~60KB worth of pixels even at 2x DPR. Both CDNs
     in the catalog (Deezer and Apple) encode the size in the path, so ask
     them for the 500x500 crop instead: same URL, about a third of the bytes,
     still sharp on retina. og:image keeps the 1000 in the generated pages. */
  const artAtSize = (url, px) => String(url).replace(/1000x1000/, `${px}x${px}`);

  const decodedArt = new Set();
  const pendingArt = new Map();

  function decodeArt(url) {
    if (decodedArt.has(url)) return Promise.resolve();
    if (pendingArt.has(url)) return pendingArt.get(url);

    const image = new Image();
    image.decoding = 'async';
    const loaded = new Promise((resolve, reject) => {
      image.onload = resolve;
      image.onerror = reject;
    });
    image.src = url;

    const promise = (typeof image.decode === 'function'
      ? image.decode().catch(() => loaded)
      : loaded).then(() => {
        decodedArt.add(url);
        pendingArt.delete(url);
        return true;
      }, () => {
        pendingArt.delete(url);
        return false;
      });
    pendingArt.set(url, promise);
    return promise;
  }

  function revealArt(layer, rel) {
    if (!layer || !rel.artwork) return;
    const url = artAtSize(rel.artwork, 500);
    const wasDecoded = decodedArt.has(url);
    const paint = (animate) => {
      if (!layer.isConnected) return;
      layer.style.setProperty('--art-url', `url(${JSON.stringify(url)})`);
      if (animate) void getComputedStyle(layer).opacity;
      layer.classList.add('is-loaded');
    };

    if (wasDecoded) paint(false);
    else decodeArt(url).then((loaded) => { if (loaded) paint(true); });
  }

  /* The list view can hold hundreds of tiles; setting every background image
     immediately would fetch all of them on load. Defer each tile's image
     until it's about to scroll into view (same IntersectionObserver pattern
     gear.js uses for pagination). */
  let artObserver = null;
  function applyArtLazy(el, rel) {
    if (!rel.artwork) return;
    const url = artAtSize(rel.artwork, 500);
    if (decodedArt.has(url)) {
      const layer = el.querySelector('.tile-art');
      layer.style.setProperty('--art-url', `url(${JSON.stringify(url)})`);
      layer.classList.add('is-loaded');
      return;
    }
    if (!artObserver) {
      artObserver = new IntersectionObserver((entries) => {
        for (const entry of entries) {
          if (!entry.isIntersecting) continue;
          revealArt(entry.target.querySelector('.tile-art'), entry.target._release);
          artObserver.unobserve(entry.target);
        }
      }, { rootMargin: '400px' });
    }
    el._release = rel;
    artObserver.observe(el);
  }

  function trackCountText(rel) {
    const n = (rel.tracks || []).length;
    return n === 1 ? '1 track' : `${n} tracks`;
  }

  /* =========================
     LIST VIEW
     ========================= */
  const listView = document.getElementById('listView');
  const detailView = document.getElementById('detailView');
  const grid = document.getElementById('rgrid');
  const countEl = document.getElementById('count');
  const qEl = document.getElementById('q');
  const sortSel = document.getElementById('sortSel');

  const state = { q: '', sort: 'newest' };

  const compareByTitle = (a, b) => compareText(a.title, b.title);
  const SORTERS = {
    newest: (a, b) => (b.dateMs - a.dateMs) || compareByTitle(a, b),
    oldest: (a, b) => (a.dateMs - b.dateMs) || compareByTitle(a, b),
    title: compareByTitle
  };

  function match(rel) {
    if (state.q && !rel.searchHaystack.includes(state.q)) return false;
    return true;
  }

  function releaseCard(rel) {
    const a = document.createElement('a');
    a.className = 'release-tile' + (rel.type === 'Album' ? ' release-tile--album' : '');
    a.href = releaseHref(rel.slug);
    a.dataset.motionKey = rel.slug;

    const meta = [rel.type, formatReleaseDate(rel.releaseDate), trackCountText(rel)]
      .filter(Boolean).map(escapeHTML).join(' &middot; ');

    const host = (rel.includedIn || [])[0] || null;
    a.innerHTML = `
      <div class="tile-cover" aria-hidden="true"><span class="tile-art mo-fade"></span></div>
      <div class="rinfo">
        <div class="rname">${escapeHTML(rel.title)}</div>
        ${rel.subtitle ? `<div class="rsub">${escapeHTML(rel.subtitle)}</div>` : ''}
        <div class="rmeta">${meta}</div>
        ${host ? `<div class="rcomp" title="Included in ${escapeHTML(host.title)}">Included in ${escapeHTML(host.title)}</div>` : ''}
      </div>`;

    applyArtLazy(a.querySelector('.tile-cover'), rel);
    return a;
  }

  function tileGrid(list, variant) {
    const g = document.createElement('div');
    g.className = 'rgrid' + (variant ? ` ${variant}` : '');
    for (const rel of list) g.appendChild(releaseCard(rel));
    return g;
  }

  function sectionTitle(text, count) {
    const h = document.createElement('h2');
    h.className = 'grid-section-title';
    h.innerHTML = `${escapeHTML(text)} <span class="muted">${count}</span>`;
    return h;
  }

  const SVG_CHEVRON_L = '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="15 18 9 12 15 6"/></svg>';
  const SVG_CHEVRON_R = '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="9 18 15 12 9 6"/></svg>';

  /* Section header with chevron buttons that page the rail sideways —
     the rail's own scrollbar is hidden (see .rgrid--rail). */
  function railHead(text, count, rail) {
    const head = document.createElement('div');
    head.className = 'rail-head';
    head.appendChild(sectionTitle(text, count));

    const nav = document.createElement('div');
    nav.className = 'rail-nav';
    const prev = document.createElement('button');
    const next = document.createElement('button');
    prev.className = 'rail-btn rail-btn--prev';
    next.className = 'rail-btn rail-btn--next';
    prev.type = next.type = 'button';
    prev.setAttribute('aria-label', 'Scroll albums back');
    next.setAttribute('aria-label', 'Scroll albums forward');
    prev.innerHTML = SVG_CHEVRON_L;
    next.innerHTML = SVG_CHEVRON_R;
    nav.appendChild(prev);
    nav.appendChild(next);
    head.appendChild(nav);

    prev.addEventListener('click', () => animateRailBy(rail, -railPage(rail)));
    next.addEventListener('click', () => animateRailBy(rail, railPage(rail)));
    rail.addEventListener('wheel', cancelRailMotion, { passive: true });
    rail.addEventListener('pointerdown', cancelRailMotion, { passive: true });

    const sync = () => {
      const max = (rail.scrollWidth || 0) - (rail.clientWidth || 0);
      prev.disabled = (rail.scrollLeft || 0) <= 0;
      next.disabled = (rail.scrollLeft || 0) >= max - 1;
    };
    rail.addEventListener('scroll', sync, { passive: true });
    // render() runs again on every search keystroke and throws the old rail
    // away; tie the window listener to the rail's lifetime so the discarded
    // ones don't pile up holding detached nodes alive.
    const ro = new ResizeObserver(sync);
    ro.observe(rail);
    // Layout isn't done during render; measure once the frame settles.
    requestAnimationFrame(sync);

    return head;
  }

  function primaryTiles() {
    return Array.from(grid.querySelectorAll('.rgrid:not(.rgrid--rail) .release-tile'));
  }

  function addExitClone(tile, rect, opacity, index) {
    const clone = tile.cloneNode(true);
    clone.classList.add('release-motion-clone');
    clone.setAttribute('aria-hidden', 'true');
    clone.inert = true;
    Object.assign(clone.style, {
      position: 'fixed',
      left: `${rect.left}px`,
      top: `${rect.top}px`,
      width: `${rect.width}px`,
      height: `${rect.height}px`,
      margin: '0',
      pointerEvents: 'none',
      zIndex: '90'
    });
    document.body.appendChild(clone);

    /* Departures shrink slightly and go, with no travel: a tile that is leaving
       is not the thing being looked at, so it clears the way rather than taking
       a journey of its own. Same ordering as the arrivals. */
    const animation = clone.animate([
      { opacity, transform: 'scale(1)' },
      { opacity: 0, transform: 'scale(.98)' }
    ], {
      duration: 110,
      easing: motionToken('--mo-in'),
      delay: dealDelay(index),
      fill: 'both'
    });
    trackGridMotion(animation, () => clone.remove());
  }

  function captureGridMotion(nextKeys) {
    const oldRects = new Map();
    const visible = primaryTiles().map((tile) => ({
      tile,
      rect: tile.getBoundingClientRect(),
      opacity: getComputedStyle(tile).opacity
    }))
      .filter(({ rect }) => nearViewport(rect))
      .slice(0, MAX_MOTION_TILES);
    clearGridMotions();
    if (!hasRendered || REDUCED.matches) return oldRects;

    let leaving = 0;
    for (const { tile, rect, opacity } of visible) {
      const key = tile.dataset.motionKey;
      oldRects.set(key, { rect, opacity });
      if (!nextKeys.has(key)) addExitClone(tile, rect, opacity, leaving++);
    }
    return oldRects;
  }

  function animateGridIn(oldRects) {
    if (!hasRendered || REDUCED.matches) return;
    const visible = primaryTiles().map((tile) => ({ tile, rect: tile.getBoundingClientRect() }))
      .filter(({ rect }) => nearViewport(rect))
      .slice(0, MAX_MOTION_TILES);

    // Arrivals are counted separately from survivors, so the deal stays evenly
    // spaced however many tiles happened to stay put between them.
    let arriving = 0;
    for (const { tile, rect } of visible) {
      const old = oldRects.get(tile.dataset.motionKey);
      if (!old) {
        trackGridMotion(dealIn(tile, arriving++), () => {});
        continue;
      }
      if (old.opacity === '1' && old.rect.left === rect.left && old.rect.top === rect.top) continue;
      trackGridMotion(
        moveSurvivor(tile, old.rect.left - rect.left, old.rect.top - rect.top, old.opacity),
        () => {}
      );
    }
  }

  /* First-paint guard: the initial archive lands in its settled state. Artwork
     may perform its one decode fade, but tiles never stack a load entrance on
     top of it. Only later filter and sort renders enter this motion path. */
  let hasRendered = false;

  function render() {
    cancelRailMotion();
    const sorter = SORTERS[state.sort] || SORTERS.newest;
    const list = VISIBLE_DB.filter(match).sort(sorter);
    const nextKeys = new Set(list.map((rel) => rel.slug));
    const oldRects = captureGridMotion(nextKeys);

    countEl.textContent = list.length === 1 ? '1 release' : `${list.length} releases`;

    // Re-rendering (e.g. on every search keystroke) discards the old tiles;
    // drop the observer watching them so it doesn't keep growing forever.
    if (artObserver) { artObserver.disconnect(); artObserver = null; }

    grid.replaceChildren();
    if (!list.length) {
      const p = document.createElement('p');
      p.className = 'grid-msg';
      p.textContent = VISIBLE_DB.length
        ? 'No releases match the selected filters.'
        : 'Unable to load release data. Please refresh the page.';
      grid.appendChild(p);
      hasRendered = true;
      return;
    }

    // Default view: a horizontally scrolling rail of album covers up top,
    // then the complete list below it. Searching collapses to one flat grid.
    if (!state.q) {
      const albums = list.filter((r) => r.type === 'Album');
      const frag = document.createDocumentFragment();
      if (albums.length) {
        const rail = tileGrid(albums, 'rgrid--rail');
        frag.appendChild(railHead('Albums & Collections', albums.length, rail));
        frag.appendChild(rail);
      }
      frag.appendChild(sectionTitle('All Releases', list.length));
      frag.appendChild(tileGrid(list));
      grid.appendChild(frag);
    } else {
      grid.appendChild(tileGrid(list));
    }
    animateGridIn(oldRects);
    hasRendered = true;
  }

  function debounce(fn, waitMs) {
    let timerId = 0;
    return (...args) => {
      clearTimeout(timerId);
      timerId = setTimeout(() => fn(...args), waitMs);
    };
  }

  /* Returning from a detail page should land where the visitor left off,
     not back at the top of the list. Navigations between the list and
     ?r=<slug> are full page loads, so the list state (search, sort, scroll
     position, album-rail offset) is stashed in sessionStorage when a tile
     is clicked and restored only when the visitor arrives back from a
     detail page (back link, or browser back without bfcache). Fresh visits
     via the nav ignore the stash and start at the top. */
  const LIST_STATE_KEY = 'pokestir-releases-list-state';

  /* The view transition snapshots `.tile-cover` at the moment the navigation
     starts, which is the moment the pointer comes up: measured there, the cover
     is translated 2px, scaled to .985, and running three animations at once (a
     transition plus tile-rise and tile-unsquash). So the artwork begins its
     flight from a slightly different position and size on every single click,
     depending only on how fast the click was released. That is why the same
     navigation never quite looks the same twice.

     Put the cover back in its resting pose and flush that before the navigation
     proceeds, so the flight always starts from the tile as drawn. The class
     only ever lands on a document that is about to be replaced. */
  function stillTransitionArt(tile) {
    const cover = tile.querySelector('.tile-cover');
    if (!cover) return;
    tile.classList.remove('is-pressed', 'is-released');
    cover.getAnimations().forEach((a) => a.cancel());
    cover.classList.add('is-transition-still');
    void cover.offsetWidth;
  }

  function markTransitionArt(tile) {
    for (const cover of grid.querySelectorAll('.tile-cover.is-transition-art')) {
      cover.classList.remove('is-transition-art');
    }
    const cover = tile && tile.querySelector('.tile-cover');
    if (cover) cover.classList.add('is-transition-art');
  }

  function saveListState(tile) {
    try {
      const rail = grid.querySelector('.rgrid--rail');
      sessionStorage.setItem(LIST_STATE_KEY, JSON.stringify({
        q: qEl.value,
        sort: state.sort,
        y: window.scrollY,
        railX: rail ? rail.scrollLeft : 0,
        artSlug: tile ? tile.dataset.motionKey : '',
        artRail: Boolean(tile && tile.closest('.rgrid--rail'))
      }));
    } catch (e) { /* storage unavailable (private mode); skip */ }
  }

  function restoreListState() {
    let saved = null;
    try { saved = JSON.parse(sessionStorage.getItem(LIST_STATE_KEY)); } catch (e) { return false; }
    if (!saved) return false;

    const nav = performance.getEntriesByType('navigation')[0];
    let fromDetail = false;
    try {
      const ref = new URL(document.referrer);
      fromDetail = ref.origin === window.location.origin &&
        Boolean(slugFromPath(ref.pathname) || ref.searchParams.get('r'));
    } catch (e) { /* no referrer */ }
    if (!fromDetail && !(nav && nav.type === 'back_forward')) return false;

    if (saved.q) {
      qEl.value = saved.q;
      state.q = saved.q.trim().toLowerCase();
    }
    if (saved.sort && SORTERS[saved.sort]) {
      sortSel.value = saved.sort;
      state.sort = saved.sort;
    }
    render();
    const rail = grid.querySelector('.rgrid--rail');
    if (rail && saved.railX) rail.scrollLeft = saved.railX;
    // Force the rebuilt archive to its final height before restoring scroll.
    // The incoming view-transition snapshot must see the same viewport the
    // visitor left, not the top of the freshly rebuilt page.
    void grid.offsetHeight;
    window.scrollTo({ top: saved.y || 0, behavior: 'instant' });
    if (saved.artSlug) {
      const target = Array.from(grid.querySelectorAll('.release-tile')).find((tile) =>
        tile.dataset.motionKey === saved.artSlug &&
        Boolean(tile.closest('.rgrid--rail')) === Boolean(saved.artRail));
      if (target && nearViewport(target.getBoundingClientRect())) markTransitionArt(target);
    }
    // Layout finishes after this frame; scroll once the page has its height.
    // 'instant' bypasses the site-wide `scroll-behavior: smooth`, which would
    // otherwise animate the restore all the way down from the top.
    requestAnimationFrame(() => window.scrollTo({ top: saved.y || 0, behavior: 'instant' }));
    return true;
  }

  function saveReturnArt(rel) {
    try {
      const saved = JSON.parse(sessionStorage.getItem(LIST_STATE_KEY)) || {
        q: '', sort: 'newest', y: 0, railX: 0
      };
      if (saved.artSlug !== rel.slug) {
        saved.artSlug = rel.slug;
        saved.artRail = rel.type === 'Album';
      }
      sessionStorage.setItem(LIST_STATE_KEY, JSON.stringify(saved));
    } catch (e) { /* storage unavailable; root crossfade still works */ }
  }

  function initList() {
    grid.addEventListener('click', (e) => {
      const tile = e.target.closest('.release-tile');
      if (!tile) return;
      const plainNavigation = !e.metaKey && !e.ctrlKey && !e.shiftKey && !e.altKey;
      if (plainNavigation) {
        stillTransitionArt(tile);
        markTransitionArt(tile);
      }
      saveListState(tile);
    });

    qEl.addEventListener('input', debounce(() => {
      state.q = qEl.value.trim().toLowerCase();
      render();
    }, 200));

    sortSel.addEventListener('change', () => {
      state.sort = sortSel.value;
      render();
    });

    document.getElementById('clear').addEventListener('click', () => {
      state.q = '';
      qEl.value = '';
      render();
    });

    if (!restoreListState()) render();
  }

  /* =========================
     DETAIL VIEW  (?r=<slug>)
     ========================= */
  /* When a release is included in a compilation, each platform button
     defaults to the compilation's URL (old singles get delisted as their
     compilations take over) and only falls back to the release's own link. */
  function platformLinks(rel, host) {
    const links = rel.links || {};
    const hostLinks = (host && host.links) || {};
    const out = [];
    for (const p of PLATFORMS) {
      const url = hostLinks[p.key] || links[p.key];
      if (!url) continue;
      out.push(`
        <a class="btn plat-${p.key}" href="${escapeHTML(url)}" target="_blank" rel="noopener noreferrer" aria-label="${escapeHTML(p.label)} (opens in a new tab)">
          <img src="/images/icons/${p.icon}" width="20" height="20" alt="">${escapeHTML(p.label)}
        </a>`);
    }
    for (const extra of rel.otherLinks || []) {
      if (!extra || !extra.url) continue;
      // Materia (materia.to) is the catalog's Linkfire smart-link; give it
      // the Materia icon and tint instead of a plain text button.
      const isLinkfire = extra.label === 'Listen Everywhere';
      out.push(isLinkfire ? `
        <a class="btn plat-linkfire" href="${escapeHTML(extra.url)}" target="_blank" rel="noopener noreferrer" aria-label="Linkfire (opens in a new tab)">
          <img src="/images/icons/linkfire.png" width="20" height="20" alt="">Linkfire
        </a>` : `
        <a class="btn" href="${escapeHTML(extra.url)}" target="_blank" rel="noopener noreferrer" aria-label="${escapeHTML(extra.label)} (opens in a new tab)">${escapeHTML(extra.label)}</a>`);
    }
    return out.join('');
  }

  /* Tracks without an explicit artists array are solo Pokestir recordings;
     only tracks with featured or co-primary artists store one in
     tracks-data.js. UPC/ISRC stay in the data but are not rendered. */
  function trackArtists(t) {
    return (t.artists && t.artists.length) ? t.artists.join(', ') : 'Pokestir';
  }

  const SVG_PLAY = '<svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M8 5v14l11-7z"/></svg>';
  const SVG_PAUSE = '<svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M6 19h4V5H6v14zm8-14v14h4V5h-4z"/></svg>';

  function trackRows(rel) {
    return (rel.tracks || []).map((t, i) => {
      const interactive = t.preview
        ? ` role="button" tabindex="0" data-preview="${escapeHTML(t.preview)}" data-title="${escapeHTML(t.title)}" aria-label="Play preview: ${escapeHTML(t.title)}"`
        : '';
      return `
      <div class="track-row${t.preview ? ' has-preview' : ''}"${interactive}>
        <div class="t-lead" aria-hidden="true">
          <span class="t-num">${i + 1}</span>
          ${t.preview ? `<span class="t-ic-play">${SVG_PLAY}</span><span class="t-ic-pause">${SVG_PAUSE}</span>` : ''}
        </div>
        <div class="t-main">
          <div class="t-title">${escapeHTML(t.title)}</div>
          <div class="t-artist">${escapeHTML(trackArtists(t))}</div>
        </div>
        ${t.duration ? `<div class="t-dur">${escapeHTML(t.duration)}</div>` : '<div></div>'}
      </div>`;
    }).join('');
  }

  /* One shared audio element plays 30-second track previews. Clicking a row
     pauses/resumes it; clicking another row switches to that track. */
  function initPreviewPlayer(root) {
    const rows = Array.from(root.querySelectorAll('.track-row.has-preview'));
    if (!rows.length) return;

    const audio = new Audio();
    audio.preload = 'none';
    let current = null;

    function play(row) {
      audio.play().catch(() => {
        if (current !== row) return;
        setRow(row, false);
        current = null;
      });
    }

    /* `timeupdate` fires about four times a second, so writing --pct straight
       from it steps the progress edge in quarter-second jumps. The CSS glides
       between values (see .track-row); resetting a row back to zero has to skip
       that glide, or a finished preview visibly rewinds itself. */
    function setPct(row, pct, glide) {
      if (!glide) {
        row.classList.add('track-row--jump');
        row.style.setProperty('--pct', pct);
        void row.offsetWidth;   // land the value before the transition returns
        row.classList.remove('track-row--jump');
        return;
      }
      row.style.setProperty('--pct', pct);
    }

    function setRow(row, playing) {
      row.classList.toggle('is-playing', playing);
      row.setAttribute('aria-label',
        (playing ? 'Pause preview: ' : 'Play preview: ') + (row.dataset.title || ''));
      if (!playing) setPct(row, '0%', false);
    }

    function toggle(row) {
      if (current === row) {
        if (audio.paused) play(row);
        else audio.pause();
        return;
      }
      if (current) setRow(current, false);
      current = row;
      audio.src = row.dataset.preview;
      audio.load();
      play(row);
    }

    for (const row of rows) {
      row.addEventListener('click', () => toggle(row));
      row.addEventListener('keydown', (e) => {
        if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); toggle(row); }
      });
    }

    audio.addEventListener('play', () => { if (current) setRow(current, true); });
    audio.addEventListener('pause', () => { if (current) setRow(current, false); });
    audio.addEventListener('ended', () => {
      if (current) { setRow(current, false); current = null; }
    });
    // If a preview URL ever goes dead, reset the row instead of leaving it
    // stuck. The replacement can be edited directly in tracks-data.js.
    audio.addEventListener('error', () => {
      if (current) { setRow(current, false); current = null; }
    });
    audio.addEventListener('timeupdate', () => {
      if (!current || !isFinite(audio.duration) || !audio.duration) return;
      setPct(current, (audio.currentTime / audio.duration * 100) + '%', true);
    });
  }

  /* ---- "Did you mean" for unknown slugs ----
     Two complementary similarity measures, take the best of either:
     - edit distance catches typos (shurey-hill -> shurrey-hill);
     - hyphen-token overlap catches longer/reworded addresses, including any
       pre-rename slug, whose tokens contain the current short slug's tokens.
     The catalog is small enough to brute-force score on every miss. */
  function editDistance(a, b) {
    let prev2 = null;
    let prev = Array.from({ length: b.length + 1 }, (_, j) => j);
    for (let i = 1; i <= a.length; i++) {
      const row = [i];
      for (let j = 1; j <= b.length; j++) {
        let v = Math.min(prev[j] + 1, row[j - 1] + 1,
          prev[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
        if (i > 1 && j > 1 && a[i - 1] === b[j - 2] && a[i - 2] === b[j - 1]) {
          v = Math.min(v, prev2[j - 2] + 1); // transposition
        }
        row.push(v);
      }
      prev2 = prev;
      prev = row;
    }
    return prev[b.length];
  }

  function slugSimilarity(q, slug) {
    if (q === slug) return 1;
    const charSim = 1 - editDistance(q, slug) / Math.max(q.length, slug.length);
    const A = new Set(q.split('-').filter(Boolean));
    const B = new Set(slug.split('-').filter(Boolean));
    let inter = 0;
    for (const t of A) if (B.has(t)) inter++;
    const dice = 2 * inter / (A.size + B.size);
    const containment = inter / Math.min(A.size, B.size);
    return Math.max(charSim, dice, containment * 0.9);
  }

  function suggestReleases(q, limit) {
    const norm = String(q).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
    if (!norm) return [];
    return VISIBLE_DB
      .map((rel) => ({ rel, score: slugSimilarity(norm, rel.slug) }))
      .filter((s) => s.score >= 0.5)
      .sort((a, b) => b.score - a.score)
      .slice(0, limit)
      .map((s) => s.rel);
  }

  function renderNotFound(slug) {
    const hits = suggestReleases(slug, 3);
    const suggest = hits.length ? `
          <div class="nf-suggest">
            <div class="nf-label">Did you mean:</div>
            <ul class="nf-list">
              ${hits.map((rel) => `<li><a href="${releaseHref(rel.slug)}">${escapeHTML(rel.title)}</a></li>`).join('')}
            </ul>
          </div>` : '';
    detailView.innerHTML = `
      <a class="back-link" href="${LIST_URL}"><span class="back-arrow" aria-hidden="true">&larr;</span> All Releases</a>
      <section class="card detail-head">
        <div class="info">
          <h1 class="d-title">Release not found</h1>
          <p class="d-desc">There's no release at this address. It may have been renamed or removed.</p>${suggest}
        </div>
      </section>`;
  }

  function renderDetail(slug) {
    listView.hidden = true;
    detailView.hidden = false;

    const rel = VISIBLE_DB.find((r) => r.slug === slug);
    if (!rel) {
      document.title = 'Pokestir - Releases';
      renderNotFound(slug);
      return;
    }

    saveReturnArt(rel);

    document.title = `Pokestir - ${rel.title}`;

    const facts = [rel.type, formatReleaseDate(rel.releaseDate), trackCountText(rel)]
      .filter(Boolean).map(escapeHTML).join(' &middot; ');

    const host = (rel.includedIn || [])[0] || null;
    const fromAlbum = host ? `
      <div class="d-from">Included in <a href="${releaseHref(host.slug)}">${escapeHTML(host.title)}</a>
        <div class="d-from-note">The listening links below open the compilation.</div>
      </div>` : '';

    const buttons = platformLinks(rel, host);
    const hasPreviews = (rel.tracks || []).some((t) => t.preview);

    detailView.innerHTML = `
      <a class="back-link" href="${LIST_URL}"><span class="back-arrow" aria-hidden="true">&larr;</span> All Releases</a>
      <div class="detail-stack">
        <section class="card detail-head" aria-label="Release overview">
          <div class="art" aria-hidden="true"><span class="detail-art mo-fade"></span></div>
          <div class="info">
            <h1 class="d-title">${escapeHTML(rel.title)}</h1>
            ${rel.subtitle ? `<div class="d-sub">${escapeHTML(rel.subtitle)}</div>` : ''}
            <div class="d-facts">${facts}</div>
            ${fromAlbum}
            ${rel.description ? `<p class="d-desc">${escapeHTML(rel.description)}</p>` : ''}
            ${buttons ? `<nav class="plat-links" aria-label="Listen on">${buttons}</nav>` : ''}
          </div>
        </section>

        <div class="tracks-section">
          <h2 class="page-title">Tracks</h2>
          ${hasPreviews ? '<p class="section-sub">Click a track for a 30-second preview (96 kbps). Full quality is on the links above.</p>' : ''}
          <section class="tracks-list" aria-label="Track list">
            ${trackRows(rel)}
          </section>
        </div>
      </div>`;

    revealArt(detailView.querySelector('.detail-art'), rel);
    initPreviewPlayer(detailView);
  }

  /* =========================
     ROUTER
     ========================= */
  /* Two ways in: this page's own folder URL (/releases/<slug>/, the canonical
     one) and the legacy /releases/?r=<slug> query links shared before those
     pages existed. Legacy links hand off to the folder URL so there is one
     address per release; unknown slugs stay here for the "did you mean" view.
     404.html sends a folder URL with no page back here as ?r=<slug>&missing=1,
     which suppresses the hand-off so the two can't bounce off each other. */
  const params = new URLSearchParams(window.location.search);
  const querySlug = params.get('r');
  const pathSlug = slugFromPath(window.location.pathname);

  if (querySlug) {
    if (!params.has('missing') && VISIBLE_DB.some((rel) => rel.slug === querySlug)) {
      window.location.replace(releaseHref(querySlug));
    } else {
      renderDetail(querySlug);
    }
  } else if (pathSlug) {
    renderDetail(pathSlug);
  } else {
    initList();
  }
}());
